version: '3'
services:
  mysql:
    image: mysql:8
    container_name: mysql
    ports:
    - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
    - mysql
    ports:
      - 10000:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: test
      PMA_PASSWORD: test
    depends_on:
      - mysql
